apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: nexus
  name: nexus
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nexus
    spec:
      containers:
      - image: sonatype/nexus3
        name: nexus
        ports:
        - containerPort: 8081
        resources: {}
        volumeMounts:
        - mountPath: /nexus-data
          name: convertir-nexus-data
      restartPolicy: Always
      volumes:
      - name: convertir-nexus-data
        persistentVolumeClaim:
          claimName: convertir-nexus-data
status: {}
