apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kong-database
  name: kong-database
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kong-database
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: kong
        - name: POSTGRES_USER
          value: kong
        image: postgres:9.5
        name: kong-database
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: kong-database-claim0
      restartPolicy: Always
      volumes:
      - name: kong-database-claim0
        persistentVolumeClaim:
          claimName: kong-database-claim0
status: {}
